# Generated by Django 3.1.7 on 2022-01-12 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numar_document', models.IntegerField(unique=True)),
                ('nume', models.CharField(max_length=20)),
                ('prenume', models.CharField(max_length=50)),
                ('data_nasterii', models.DateField()),
                ('adresa', models.CharField(blank=True, max_length=100, null=True)),
                ('tara', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Valuta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=20)),
                ('tara', models.CharField(max_length=100)),
                ('sold', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Zi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Cotatie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curs_cumparare', models.FloatField()),
                ('curs_vanzare', models.FloatField()),
                ('data', models.DateTimeField()),
                ('valuta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casa.valuta')),
            ],
        ),
        migrations.CreateModel(
            name='BuletinDeSchimb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.CharField(choices=[('C', 'Cumparare'), ('V', 'Vanzare')], max_length=2)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casa.client')),
                ('cotatie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casa.cotatie')),
            ],
        ),
    ]
