# Generated by Django 3.1.7 on 2022-01-13 08:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('casa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buletindeschimb',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='buletindeschimb',
            name='suma_lei',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buletindeschimb',
            name='suma_valuta',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
