# Generated by Django 3.1.7 on 2022-01-13 13:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('casa', '0002_auto_20220113_0817'),
    ]

    operations = [
        migrations.AddField(
            model_name='buletindeschimb',
            name='ora',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cotatie',
            name='ora',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='buletindeschimb',
            name='data',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='cotatie',
            name='data',
            field=models.DateField(),
        ),
    ]
